apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    environment: testapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer