apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: testapp
  name: testdeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: testapp
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        environment: testapp
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
